<?php

/**
 * @file
 * ${project_description}
 */

/**
 * Implements hook_help().
 */
function ${project_name}_help($path, $arg) {
  switch ($path) {
    // Main module help for the block module
    /*
     *case 'admin/help#block':
     *  return '<p>' . t('Blocks are boxes of content rendered into an area, or region, of a web page. The default theme Bartik, for example, implements the regions "Sidebar first", "Sidebar second", "Featured", "Content", "Header", "Footer", etc., and a block may appear in any one of these areas. The <a href="@blocks">blocks administration page</a> provides a drag-and-drop interface for assigning a block to a region, and for controlling the order of blocks within regions.', array('@blocks' => url('admin/structure/block'))) . '</p>';
     */
    case '':
      return '<p>' . t('', array('' => )) . '</p>';
  }
}

/**
 * Implements hook_permission().
 */
function ${project_name}_permission() {
  return array(
    /*
     *'administer my module' =>  array(
     *  'title' => t('Administer my module'),
     *  'description' => t('Perform administration tasks for my module.'),
     *),
     */
    '' =>  array(
      'title' => t(''),
      'description' => t(''),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function _project_name__menu() {
  /*
   *$items['blog'] = array(
   *  'title' => 'blogs',
   *  'page callback' => 'blog_page',
   *  'access arguments' => array('access content'),
   *  'type' => MENU_SUGGESTED_ITEM,
   *);
   */
  $items[''] = array(
    'title' => '',
    'page callback' => '',
    'page arguments' => array(),
    'access arguments' => array(''),
    'type' => ,
    'file' => ,
  );

  return $items;
}
